-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 18:23:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `idRol` INT NOT NULL,
  `tipoRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `userId` INT NOT NULL,
  `fotoUsuario` BLOB NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fk_idRol` INT NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `idUSUARIOS_UNIQUE` (`userId` ASC) VISIBLE,
  INDEX `fk_USUARIOS_ROLES_idx` (`fk_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`fk_idRol`)
    REFERENCES `mydb`.`ROLES` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAMBIO-CONTRASEÑA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAMBIO-CONTRASEÑA` (
  `cambioId` INT NOT NULL,
  `tokenRecuperacion` VARCHAR(45) NULL,
  `fechaHoraCambio` TIMESTAMP(4) NULL,
  `USUARIOS_userId` INT NOT NULL,
  PRIMARY KEY (`cambioId`, `USUARIOS_userId`),
  INDEX `fk_CAMBIO-CONTRASEÑA_USUARIOS1_idx` (`USUARIOS_userId` ASC) VISIBLE,
  CONSTRAINT `fk_CAMBIO-CONTRASEÑA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_userId`)
    REFERENCES `mydb`.`USUARIOS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EVALUACION_ESPACIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EVALUACION_ESPACIO` (
  `evaluacionId` INT NOT NULL,
  `puntuacion` VARCHAR(45) NULL,
  `comentario` VARCHAR(250) NULL,
  `fechaHora` TIMESTAMP(4) NULL,
  `EVALUACION_ESPACIOcol` VARCHAR(45) NULL,
  PRIMARY KEY (`evaluacionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ESPACIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ESPACIOS` (
  `espacioId` INT NOT NULL,
  `nombreEspacio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `tipoEspacio` VARCHAR(45) NULL COMMENT 'si es al aire libre etc',
  `disponibilidad` TINYINT NULL,
  `ESPACIOScol` VARCHAR(45) NULL,
  `EVALUACION_ESPACIO_evaluacionId` INT NOT NULL,
  PRIMARY KEY (`espacioId`, `EVALUACION_ESPACIO_evaluacionId`),
  INDEX `fk_ESPACIOS_EVALUACION_ESPACIO1_idx` (`EVALUACION_ESPACIO_evaluacionId` ASC) VISIBLE,
  CONSTRAINT `fk_ESPACIOS_EVALUACION_ESPACIO1`
    FOREIGN KEY (`EVALUACION_ESPACIO_evaluacionId`)
    REFERENCES `mydb`.`EVALUACION_ESPACIO` (`evaluacionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVA` (
  `reservacionId` INT NOT NULL,
  `fechaHoraInicioReserva` TIMESTAMP(4) NULL,
  `fechaHoraFinReserva` TIMESTAMP(4) NOT NULL,
  `estadoReserva` VARCHAR(45) NOT NULL,
  `USUARIOS_userId` INT NOT NULL,
  `ESPACIOS_espacioId` INT NOT NULL,
  PRIMARY KEY (`reservacionId`, `USUARIOS_userId`, `ESPACIOS_espacioId`),
  UNIQUE INDEX `fechaHoraInicioReserva_UNIQUE` (`fechaHoraInicioReserva` ASC) VISIBLE,
  INDEX `fk_RESERVA_USUARIOS1_idx` (`USUARIOS_userId` ASC) VISIBLE,
  INDEX `fk_RESERVA_ESPACIOS1_idx` (`ESPACIOS_espacioId` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_USUARIOS1`
    FOREIGN KEY (`USUARIOS_userId`)
    REFERENCES `mydb`.`USUARIOS` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_ESPACIOS1`
    FOREIGN KEY (`ESPACIOS_espacioId`)
    REFERENCES `mydb`.`ESPACIOS` (`espacioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
